-- AlterTable
ALTER TABLE "Subscription" ALTER COLUMN "ended_at" DROP NOT NULL,
ALTER COLUMN "cancel_at" DROP NOT NULL,
ALTER COLUMN "canceled_at" DROP NOT NULL,
ALTER COLUMN "trial_start" DROP NOT NULL,
ALTER COLUMN "trial_end" DROP NOT NULL;
